version: '3'
services:
  app:
    container_name: currency-exchange-app
    image: currency-exchange-app:v1
    build: .
    links:
      - redis
    ports:
      - "8085:8085"
    volumes:
      - ~/docker/redis:/redis-service/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"